

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CadConsultorioMedico
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class LabConsultorioMedicoEntities : DbContext
{
    public LabConsultorioMedicoEntities()
        : base("name=LabConsultorioMedicoEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Cita> Cita { get; set; }

    public virtual DbSet<Concepto> Concepto { get; set; }

    public virtual DbSet<Doctor> Doctor { get; set; }

    public virtual DbSet<Especialidad> Especialidad { get; set; }

    public virtual DbSet<HistorialClinico> HistorialClinico { get; set; }

    public virtual DbSet<Paciente> Paciente { get; set; }

    public virtual DbSet<Pago> Pago { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<Receta> Receta { get; set; }


    public virtual ObjectResult<paCitaListar_Result> paCitaListar()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paCitaListar_Result>("paCitaListar");
    }


    public virtual ObjectResult<paCitaporFechaListar_Result> paCitaporFechaListar(Nullable<System.DateTime> fecha)
    {

        var fechaParameter = fecha.HasValue ?
            new ObjectParameter("fecha", fecha) :
            new ObjectParameter("fecha", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paCitaporFechaListar_Result>("paCitaporFechaListar", fechaParameter);
    }


    public virtual ObjectResult<paDoctorListar_Result> paDoctorListar()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paDoctorListar_Result>("paDoctorListar");
    }


    public virtual ObjectResult<paEspecialidadListar_Result> paEspecialidadListar()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paEspecialidadListar_Result>("paEspecialidadListar");
    }


    public virtual ObjectResult<paHistorialClinicoListar_Result> paHistorialClinicoListar()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paHistorialClinicoListar_Result>("paHistorialClinicoListar");
    }


    public virtual ObjectResult<paPacienteListar_Result> paPacienteListar()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paPacienteListar_Result>("paPacienteListar");
    }


    public virtual ObjectResult<paPagoListar_Result> paPagoListar()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paPagoListar_Result>("paPagoListar");
    }


    public virtual ObjectResult<paReporteCitasPorFecha_Result> paReporteCitasPorFecha(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
    {

        var fechaInicioParameter = fechaInicio.HasValue ?
            new ObjectParameter("fechaInicio", fechaInicio) :
            new ObjectParameter("fechaInicio", typeof(System.DateTime));


        var fechaFinParameter = fechaFin.HasValue ?
            new ObjectParameter("fechaFin", fechaFin) :
            new ObjectParameter("fechaFin", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteCitasPorFecha_Result>("paReporteCitasPorFecha", fechaInicioParameter, fechaFinParameter);
    }


    public virtual ObjectResult<paReporteCitasPorFecha1_Result> paReporteCitasPorFecha1(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
    {

        var fechaInicioParameter = fechaInicio.HasValue ?
            new ObjectParameter("fechaInicio", fechaInicio) :
            new ObjectParameter("fechaInicio", typeof(System.DateTime));


        var fechaFinParameter = fechaFin.HasValue ?
            new ObjectParameter("fechaFin", fechaFin) :
            new ObjectParameter("fechaFin", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReporteCitasPorFecha1_Result>("paReporteCitasPorFecha1", fechaInicioParameter, fechaFinParameter);
    }


    public virtual ObjectResult<paRecetaListar_Result> paRecetaListar()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paRecetaListar_Result>("paRecetaListar");
    }

}

}

