
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CadConsultorioMedico
{

using System;
    using System.Collections.Generic;
    
public partial class Receta
{

    public int id { get; set; }

    public int idHistorialClinico { get; set; }

    public string medicamentos { get; set; }

    public string dosis { get; set; }

    public string indicaciones { get; set; }

    public System.DateTime fechaRegistro { get; set; }

    public string usuarioRegistro { get; set; }

    public short estado { get; set; }



    public virtual HistorialClinico HistorialClinico { get; set; }

}

}
